### PR TITLE
Fix multi-compare phenogrid

### LINKED ISSUE #656: Fix Phenogrid MultiCompare results display
Something is fishy about multi-compare phenogrid that doesn't quite make sense. 

Possibly in the UI component, but I suspect it's possibly an issue with the API method. 

See for example the difference between first column in [this search](https://dev.monarchinitiative.org/phenogrid-search?object-group=Human+Genes&subjects=HP:0002616,HP:0001763,HP:0004944,HP:0010749,HP:0001533,HP:0002020,HP:0012450) in phenotype explorer, vs. [this multi-compare](https://dev.monarchinitiative.org/phenogrid-multi-compare?subjects=HP:0002616,HP:0001763,HP:0004944,HP:0010749,HP:0001533,HP:0002020,HP:0012450&object-sets=HP:0000023,HP:0002616,HP:0012163,HP:0002705,HP:0002138,HP:0002105,HP:0003549,HP:0200146,HP:0100775,HP:0002326,HP:0004959,HP:0004933,HP:0004950,HP:0004944,HP:0000766,HP:0000822,HP:0000978,HP:0000965,HP:0005112,HP:0005162,HP:0001677,HP:0001643,HP:0001659,HP:0001640,HP:0012499,HP:0011106,HP:0001763,HP:0000525,HP:0001166,HP:0001297,HP:0002875,HP:0000316,HP:0000098,HP:0002650,HP:0002140,HP:0002107,HP:0100749,HP:0012763,HP:0000278,HP:0002647,HP:0001647&metric=ancestor_information_content) call using the same phenotypes from subjects (set A) and column one.

### PR DESCRIPTION
**Pull request by glass-ships**
Closes #656 and #697 

- Revert typer from 0.12.3 to 0.7 + typer-cli
- Swap `object_best_matches` for `subject_best_matches` in `compareSetToSets`
- Add Ancestor IC to cell hover info
- Add `metric` parameter to phenogrid search and multi-compare URLs 
- Link to `phenogrid.md` from `CONTRIBUTING.md`
- [x] Update phenogrid documentation about making iframes a little
- [x] Add test for phenogrid content (@kevinschaper)
- [x] Change example in phenotype explore / testbed (another PR? this one?)

### CODE REVIEW

File: frontend/src/pages/PageTestbed.vue [hunk 1]
```diff
@@ -251,6 +260,38 @@ function sendMessage() {
   );
 }
 
+/** Same as above, but for multi-compare phenogrid */
+function postPhenogridMulti() {
+  const iframe =
+    document.querySelector<HTMLIFrameElement>("[name=pheno-multi]");
+  if (!iframe) return;
+  iframe.contentWindow?.postMessage(
```
Comment (kevinschaper) [inline frontend/src/pages/PageTestbed.vue:270]: Even if it's just hardcoded here, we should swap in the values from the multi compare request in the fixtures

**Review by kevinschaper — APPROVED** [review]
